---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-registry-auth
  namespace: default
spec:
  encryptedData:
    htpasswd: AgB62oQ2524ZoR1mONu2Yxlm/5r89SJrxufcnOE/ZOuYGjLqx0FP0s+UYVkl2okNa6l0FxnaAXmVQQF3tvSHyibHcfX2PxM2jQbqelgzjYgHABFHfWluiUeflQNpRXwEGOd/uWl8gh4e9vMI0AqWJOy5IlHuf63bQHFIb9NVzZT3uBOgiKz3I0fr/Y9ZN4ziAOcsq8drgi5NphxiXaTve1WSyhvgIid873+g7stHgBVjcUuKYKN16VqhwTLSQsnLLV4hvS37hUgqH5Vm0sZmY2GYEeNtkA8QeD2LVvvrOwBLOgQfYXP9rdYl/CG2vr6x9u0P5+m6WG8anpbTyTCNdJka6E5HBKmQUQPqLSUVXd1ZAEcpB/tJ0g1H21KoM8796gvWFO2cZHH02fnIgrRtZSW8Dy08+ILDjnBPoik6JJlFpWkqvPBrpHka5gRxI38qmO+JPgbXncaHId7HSyKIuSefxwVC8M9aAeEDtGrqRNaRq+4/dymbOBRofUWl6C8aYE0iCviecpfoGpT05/3GajKjWsaoSLQ1hktzAZdeJwbDCXErmm50jcUhuzzu8g86CWXD5nDnebNTyDXTS/52yjzzoLjgD6Gtnj37cqfh67LjBGvFYNxSpGTrPwhdVHH7H1cUFNyfty3ci146EdT3ipQ1llVsBHgMh+9xy1MMRQfRGSenhlo/0w4BOvSqo2JEuSdV/QmDSg4sHOXF7PKpgSNtCIOJY4KctaU6rWlmkoGe2ebgwWpTnLgPj/ccukxMEaXHiC/FV+UNm3wXJrC5n7kvT+8=
  template:
    metadata:
      name: docker-registry-auth
      namespace: default
    type: Opaque
