---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: rabbitmq-secret
  namespace: rabbitmq
spec:
  encryptedData:
    rabbitmq-erlang-cookie: AgBlR+vXfMxOa2+b3VMh4QoN5QoxBLpLOsRYN/sKrsupt4RgVUMY7B8g02w8dW6SmzG/vXAqUua6aY61ov7V6SVSFS0SqKKVdSeHrU8Khb2fvAFIrbmv4FQCtjkOW4Aw8NpsrqbFq6YBiMSFFr7zJYgZKUcwDe2BeWHXxawUufjcMAZqv0IQI31hDv0nfRJRE+89as8ymSnafxNNLZdXDVVtyuzUc0r4Swk3syKa9q0h+HoIvHJlSkemHAdz9wH2KgwwJYjFRZDKH1+X8WpJ50UB8/hW7kOFz1yCnxy8lcWZH5CRZlYv8hZEblgPHgKpkB2ovv1YuQtImoLZzelkfTYazP5h+t8J86Sn0ynyrUzqGaAT6Kqbva1phyrq4f8vUeTafHr5x0IVIJnIvUrJSFK4P7JE2QSF6APknaeYI0AJWdLFbFclSvuQ8xNvzsJ3kWPevU8AXjicsVT3EQueRlvElSruWYn+HC/ZG6kQAGKFEsp0zXL5uJLzowhD76T53VTI9oTk+vdC0Cq1Z6he1vRRacuTtD6iyX2Z4hiTxLnkvjlI8Iz2iysYATpXr1hg+xuzKrycl2wZeFhwuW41k8aQf/Itf9WEgCg1ImxD6YmzvZCKIiq5Pe+Fk0mjQrnh32nfz0WNZITude57mbB4r4srPtyvuoy1Cqk8dSPWVMuVP8gO97BIipSqmL6HWD0NjHk4JFz4UwQ8iUN1WlyveN1fTeVAI01JL2lqvw==
    rabbitmq-password: AgCY2+o+lMKA/od6TE9qvm7K3pJteInyHYNGuJdyMwC8a5X88H3JyZyAly0aTw/UPRVjWcyu96yK59ON/2SL0ks4NhAclLkBiRh1HgB6Vv0NY6e+f5e5oTFqv5dYH+404c5TmztFY0R7vB9VNcqoUeRjUNk2+SRjol20GRMshM2zZxuwf+WQZaSycO6138KhcpzW8+oBdZLnwy5YzTWKMJptRNtqEjUMjHH5a83J7W6+jYuCo9rHpoNn/k4Cv+mgKsSmY6GHxHOYvBY7twauOfH4zxvxyalsaci861svBvCTD5lv+DYsu9zd7QAFSXD3fr5whYy9YdFu6kLfKb60sH6GnoCfW979+O9RenoQZbTQcUvpCuIS5hFDlZl1NZTZaoYrPvHRl0dEmAaPPLCCOBBpBKnDpv0vqCJzVAfn5POkZUAEvbRDP4kTRL1NN/9ABQAezez53rjad5vmj0TYa17asro/gOweh5Ll6yA25tJ3sed0MGRzWLg84cXXmbju7LSqOvp8A/qhdGaMPqzHPMxWouMUxX2stgjY/QE4qANHSclNiJcbgDVQXJJLdu4lAjdZ1mQKQ3Olk/F1/ggoZ+Qn7eroUEot+3U4bNFrKroDybCM03/UM9NWLvMkkw8gME1xrvgtPzYkRMdEfmlfXS5HA1et7axNA8Q5iRB0JpUxLeQxWrHfQfV5Z2cskEKhxEIdMsy/5SDMZwskxACY/Z9f
  template:
    metadata:
      name: rabbitmq-secret
      namespace: rabbitmq
    type: Opaque
