---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-staging
  namespace: default
spec:
  encryptedData:
    redis-password: AgCmOZPJmaH1KwpUyuSlCVLdMGT5o9G/WZYJnsgWSdEB1ir8x1PEeRJ0v0fePnW0t25vqi2Gz2EWEOcynmaw1WWzl3Tf1UJAD2Zfu/DQBZuX08AvFF1Jnx1w+qIXXN08nMULrAm+0qKwxGS8Fge3AZBxvLC+VQA44XKkAAmK5R9lyNGCcS0+I2TaM6FIYWbQ1S3O+P+YAqkah2pI1hp/h8ilKQkv8I66uipyWkJ4yVfPrIoBGbJAI/UlDAyGYPMuP0+2XPiP1dQF0GKvCtgG2q5vn+sw0s0Zz3bWH5Q+Jx2cxcd+nPa66V9cGmS+cWKojD0TpUDqHb9mYdfKUMl6Y1Vjbiq8DCZPPGxoqs88W++cm2po6jIYGMvs++ZJKmErwQV1LEVOsYfIUJVIknZz3p7FT/3yXcp720Ism3VGF82CrdQQWjj8RMC3XaKRTwiuCB2ObYZfr16B0zW6ggGW5HPycZTi0Vdx+26NZ314/Q4fuliw/KhIi4XHTkciR+j/W7Ne43o6E5UhrbypoIA9nucLdzhz57KFPXiVmOZulFq8l44/OQUQC0VNbpRMd1DGpv3+O6Qk/Ct2l5Ht75uALfZcIGNbr+H+29whP1sN3h5AbWmkvVoDGejezUJVbbkcogb2jle9n4UbdLF+CrrR0m3cwSm41HwBuWibTb1jiQnCvoj9s6/S3L+uLjbvA9hgZZST5UsA4y1+3Re8WrLbI+GP
  template:
    metadata:
      name: redis-staging
      namespace: default
    type: Opaque
