---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-registry-auth
  namespace: default
spec:
  encryptedData:
    htpasswd: AgBaeM/pGu/hF3Iq1z4Gwv8ElS9C6AW06UNs4V9uCt49Z3hX7IkT4HG8YWwEH6pmAjkGxq1N8As+3Jf8Ogiub8IhFnLtM5V9AsHj4pigvYMELRCi5EELgUNrSUhtXuPUQPn/xaNMTfHdQrQDn23MplfHWMAqzmy8gmZeDroq06bRHORdadH0eUkLQneSbJ1zY9hB5GZjmsRH45N+pPPnpPk1tenRtUyvinTBB21fgRAfZloYEqCvQM/XRdfNgZQXRN3yac7f+UTAlJbR+NJyRIVnLoEWjk2C+Ox2xMBzxOENhxU2AcSj+D+6x1QwN/IXIEajcrtqIRy5VIgTKJXtTVpQLrJglq8hAjPyMMDhgN3iB9L5eLwhn5N3VmcUvkLhnyMC3gc0fAs9DCpoGGyFTsxbzEkX9G7s7UX5u76v6UrHjpTxIaqIZ5tDt2sFgaUN4vH+VgBBurg0QsPMnZLN4RUbjIpt2mNI1wzgGD7CaK/3Bt00s/zhHnqWKVbc0HIdWZ2v42DVb6J5sGKFwAy1AjZAvZMUv+8oNbiaCVubZot/VMmpxpSDfQBF4pwH3UOsvLZDrpJhQSrtbVW8/V7vVXtbx/7VDLCphGLw5HBxpvf4SVDEmk9RWbP2sga3CUimKSrE1HfffvSCsUrgVd3w3/WEmVpID/mfKb3Eswbvp8UQR5W1tvT2g/R8ZLyXsiIchA0n4an+1C6Jl4qv3m0+iKEfYg5qw8KtxM8UUSxuHcBjxTh2whJsBQR9TW4vKX6JYkzNQHZeVBxya/j7acEqWfjIwYQ=
    http-secret: AgAKjOKoCICn8/u9ME73qwFh/5iZ9tRYiFWnTkkOxlLLhmjLjD5lL4gYma0uMOLtvmxXpnx0r99Z6HL/OT/Bp+HyIwNetamgDj5/C+YxyLaMknJxQs1DMipVPIykvUGg4O+Pue0T3uy8irskQ25Uk1A1moNgco7ElKs41MiEmqZJgKcl1TLWwoBLquaAnow750N3H6dRVUoSZNR5/RGUwdgMO3/2X5D2F6G0DpJed9LnEgIIJeYn+15oC5dHIcccW8WO37Nr1UaCHBJrzdEdq8w8lkQTJYiAYNtGcW4jLoiD3xHmwnvdhlovnE1rfpiobLfrVWq4rHewIRJkLpp6sC0hXjzAEpkD2hCG2fN71O0zHxIje5NRDKeKKlgDHRP4RlN8oxQreXKLN7jI7GGhafZ2vg275zWgPPiwZ6rjBLQJ7v90QRMhdvjEx2S4GpyfjHKK1h/Lc9CXwo/HMy9Sy39irvJ4DDaJD6hub1yCQ7DiUoT+YZopJHO4eNFTX40fsCYN0AZsw96SIW40sgRPtjXz4DFdK6ZIWXMdeTXiYFv5GI81BdhVKDV6UZ2WPDC5UUfcoHxoEA5FREUs4wIdBKUJVAPwUY/CVmJhXTwZvX9sw+o9/6J0D7r91JZ8LTVbwrSUClrxhg8/xbok5lXc5g8VqEgswrheQPqeBFuifeGR7k68L0bH9lMy0AdV6ekEeA7cj/ADzxzkBXWcw27JVQHbocgWUwKfBpA5oUSp/ufrGrk8RkUMwsBGiaQ/93Wgtqwn20zd5e300lDBNPSSnJjk
  template:
    metadata:
      name: docker-registry-auth
      namespace: default
    type: Opaque
