---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgCLS2uuluJ+pYDqmyetawik97jErD9JJ6+yefr1y1Y2nl0Dt8d99BPn1W2abuXR+emC9eYEq1/9VfbS++59sWvy05aLK59eny0vSFowq28TN5HUhJW23xgT0GmiDEWuQqyKpee4FfA+GE5hkTbyGMOcwAtNunweNb35CJmIC1cygSC0bIBg8ottXkgUrZEFZYLZU2Hr7E1A1KsuKc65lmqiJRKkenHH/NMcEmeDrjGxoiTFwPFpJb88yl6v8/EODMpmYkRF8WhgfKIZBiUpM+3mljYMilaksL+2CKgl6dwVmVvD7uTNG3/pHKIVpwb6UI3GGj2YbOK38I5DnU6YIqOxZ7J5g9v/SUEpFkqfQpCsAJItiV9+663yXmL98psb+wVW1xvGEaeVcL4Mglbg9932hWOpsqjvrEYLh+LfHgVhntxEHODEj3HQrBwD0K8m5w9iuWAD6tPf2gaKiuS+iE3a6WHvTEIHcTXLiRPp19fevG9/jwj50Tdz+++SVktkyeCmLipw75HbuZjbKnRYbjdfz7Ggh+Sr5kJxe2ZS1clrz4eYLbNMwugDa7w9KifEhJffjTzaEGnzbNsMRysr3mPB9JR1wSaRXM3/udokqBRvL4/zeBzTc2kIziecHQNaOaJYZpOKzQzAz/K5XMgVGWF0w0PGG6HQpQSFH02nzKwx9lUDrJO/8iGnSOR52t+LAfVovGuo7AIC4frqLRE=
  template:
    metadata:
      name: redis-secret
      namespace: redis
    type: Opaque
