---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis
  namespace: default
spec:
  encryptedData:
    redis-password: AgABIcWiOlIU7Svtzgq2E+Yhqmb1SAGkIza0lcSjdyJemzwJvnGhCvvMtAyBt5k3cUA1x0ffqi5UJsjSCyyuwXQv4xEgxfzVizppia6OBlLBWy/FUU5MHrfpBRh9hWwQ5EZVg9iYb9shJ3fJE56fMda/twzxI+wIwujmeatgYLkjH7VZFkDm+T6xpfZubBFNcGsO8o/ZdMvJk9Fbn2uXGl5LOQ48WOhMt9q6z2R+5LgDxg/MoPpr1pdk6FCqehRkNpcz+KIViZfQmIFtmMKvzQeDUVMafRaGtAKdLEY+3gmSQVUCAPbjLTukkMZIl02aMxEwHLm31Nyt7xA6qxqP1iOZlfLkH0Z7FEmDpkbS+KffZ0fjMWNtZ+XT4S18UTjLTwfnxhoQQNkzHcJIABr0fbt8cSPKeZEQNfIvq8bZGSgWN8Ln8NRTDBr+cuiGFNhYBby4z7fr3YAAOLIvgjEdbsibynBxKD3WXJQxfBQx+5CjHNlfsgAIIJJB0A1m9/U6HbnxATfokH2GJaRu3MwCyIeQLUSD2F19laJcsTta2lGX93VSsS0WY+8pFwEG/DXNJZbkbFHB4KQkqf/bRnB2WR5+aHTr4PG/9QpJphy9q6r8+ScHVWF5ceN+X3tQs8Ky845xcP5db9PfJImNrcvnGUeiFUpH9HYyBqHPIt4NHOvKhudzucozeKueFdATJqv8gHLfnbIpwzXsjrnZ/RT5SMjO
  template:
    metadata:
      name: redis
      namespace: default
    type: Opaque
