---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgBKk7frxEV4ILmIYpGwUsp/w3n6KYoGya1PLpVWgSSgVLs2MQpwmzTLjzX8We+3QbEN3z1VT4nVhqsQnDUJczbiP3xRm2T5Jms5e7wnXe5st2fXus6uoCVAm8w0dQEPlhR66CawRHDTNmpzQ0DRdAkuxSVgoUm07Iu/K8uGtllF4yX99gaYz3ENnESyk14R5LnGORytsP1M3zgDYUVFnbre8ykpHX5AP0chPOb9BWJuXcfdjKYQ3a2dJqNCigpMzgXove/Vd57tik9dphi/N83UykEoyHFmRnrGpPe6hcV7I5KO4MQUmOkIALgPO1dTtZpOgiRkcxX4Kks5pDPq6jhRx0kVaCeWckTquryDzRvjUMACXQ6M/69OZtY87Le5Km+KDlmpIhV+wYgCV+EaaOc5XzsnJN4NPGCX+j1IamFeEYdrF7plQl1vf+A98Tc7o8E0WiiMGSjz0UU3H7jDyOaSspJKlOHmQIsRy1YFpZl60wLCMtfXmFSVEZPNDu3/Au1vz8CMKljrb3Ql9g0mAwkmu/Z/l1JLUjAnuvRqhNLa0efrEXytAReMEilAj2jNVfxQMebtXv5cceDJVTrHCUwIniPGO1bgnD8BOKS8dTbOh0POnqH0E9914sFde1d7Z5Ssmx2+YalJLTeHfJMwfKtaxD8GU37YQbxparcCoKeIgz350D7bOjEX9IHAAl3+JGZe7DzyW5Ix0tnV1d0=
  template:
    metadata:
      name: redis-secret
      namespace: redis
    type: Opaque
