---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: workout-backend-secrets
  namespace: default
spec:
  encryptedData:
    database-url: AgBRTp0qJAMoWZoqBtRqdTCTaCwHxuuPPbrfp/E957jZfAR3QBZCBUdZYqJfZi39HUOdjjfHlbVpYHYG1UJ+Z0ZZIppkdXHwKOipm35lYmNVERa17CSAbbULHKoaTzWiwvbKn2neiUJJKTA3+cjgXIKCf0LAJlv+HAF/kFHBkb+elKsofJASekEia0Yr7L+92VyWG49fFsJgBXVsPPqWh5Bi6BX5Vaagj5Jxz3s+TPY1W6GEUhil2vJoA5YRaHoKiIO9/rRxujgb/+Q1LYoK6I576dNJeda8xQFX7l21CLhGJrOW7U6GV4O7tNwDIm/KEAvI9hsT6JFXdlWFEYnXlBFGzlxCceuvuaCuw2DGnwySe8LjNenw47Ktcb6gwndofwWTNIFPsfCgfBAm4QRTlyxrl7TWvXaPMkg8ZUtYJHuBFfg0Ge6BvsaWv338G34jQGtMYKF33txmL1T47QtQg4mmJjnCGLSdFKiQr6pMU2hsoxAgIHHre1aSLIHTekfCEaBACNI1FX6MP3SGy4QwDu8ldCFMGNJdnDn2cemqlz/yW6kXmOhAR7UJuXw+EpO4KXCAXAwwQc73gHP5CNkDa8fSptBpIFzk0mFm24I8W7VL3P2rpAPf+/IOX3/YFOFqQH8wFuZQjd85nUgW5UeoRofN2tFGtaAL8vYMK7f5l8UaASonb+S2BLPWvWH/Ee/M+RnCoWixUvauTQ2FbVNP7XrbvzO7Uuup1WJfbVGAwe1SHaN7cgEDxwnpHGhaNsCOSfhBHKf2rkPIjoWXKpvumGBCglLXzI7Cpp9q2ynbBcnrCEQX2tBTnYIsf7UuXOb4oQPVPiwq
    secret-key: AgCIvY1ALklt9ivCOxgyxggtBvEF2TLZDnV5UhR4eIdtQZ5AkIvaNmCeQxo7rohs34le4IjOog9xLSaXdvZDJG59oNmCrzKZu4kYyxV6E7uQCapUHhrOHh9JViPD0IeuFroUYt4ObLUqPkH3Cy44J/JiBbQQ12KwJCbYUKGR1QOjM9C1ogub6P4RCGHFjdJhGi7tkHagJ6qpKQgGwNvpTRfAbMoZMYP0sqmRczw+ZLYvL7BLaVSxKgdybpctUZFpyMxihJpry1RDVKDkbCcBjh5QRDBxdUny5Z37CC/icJVyf6WhSvg1DG1T39ioFFeuZT+5Ji/OX3/45vmCxIsW2xSO4P1Q5eMSIlZO+WAyz88Vw1/zWJBFgOkCy/wTotI+uJ53hNoSXiLezGadTAlQ6eylXed4oJF84TCeCwZUdrcDY4e+igIRJRxmx7ZREDZ5JMJucos1BoPdBk5uzfCH1ob0g6P2ixnWTk5g4Gp0StTYNFKdXKtCYKUAZ+d/YqpnpmsxfV+BGMNx8YIP6sRmJSsjiT2sR2+6Uj+F+aANlmFlML39+hTkydMiLNM81zZ1mEMF+893gjx1pzAySAr7Vgx9YHZp7ezdUMO6GbTJy8qWqGDXEv95OINXtOB7IxuiejHEGPPyG0jtxmzD9MuR+pvC60NAeks5s5ZAhvn8Wv4jbK4M0n9XNTOhWvVUKQX0YZhH5XNL6YvV+f5rrVmpeXUJ89Ra6688ySYnGFuNqOSF5v8kpEGkMaC9V39O72auXIvqfsBtl3Kj7OKUXgFtEYvl
  template:
    metadata:
      name: workout-backend-secrets
      namespace: default
    type: Opaque
