---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-staging-secret
  namespace: redis
spec:
  encryptedData:
    redis-password: AgB8W5lWH1ElOzkrb1bxP3H1yBek7vy7l1BGl3VywRnYaAHPgdT+DxsSmaAWu/A9Jch2n6fKAVjEj6BvzdW6sO/BhD0v0uL7gy7KoBftHG8PqUetfRvsPuInAE8SUPMeoTBSDBF7QAkYK7gAfmtvn6qQA/fAl2LZY6XDRbnD+EX+gAZ6bvUJB8mxAhCIMI3ZWmxdA5XeAJukw81QezgG1TeWge9J08domucr35QaZdQ2Nvqz53kcG4slgdGXdZaI21l0EChkQwfrw6OR44e/FCSrBxC3mG+umy/mQaE7cUpmS0Y1SjDFNeqO1MbQ3RWU3WnRYn+m68vOkUGpwfRSfRugHZiIUBUSvaUvo+aHIMN7wv4phYwLI9Vw6EteEUtFE4EHz/dVEWJq6J1o7e8gZgWYzkxQbRXeUGqNLpj0yOc/xSKlkkBG0WhuZ7u7xBiXfUfu1JsSCnmSZy68x5/KTQ3AZIeaEcEgLYwzOIY5A6VYAEljie5JTILnriXQE9qjEB2VfMg0SbG1jbEOy35tkbFR3Ks2ZqIi3torDT/+zNjigZZThId+bJbaYqYYgXECj42YdcD+mlIYi6Dut0cZ1R21ZMKn9Qs5WtDpkFoFN3VzK2HuTYZJTUGWvn2yK5eSkNJwr/GxPl2xcX0WJVVlt8IQITwtSZrnCdvXlyomkpgKm96Ndkfj2OBs5HxnGyX+A5JFKjoy9l/ikz+QjJg=
  template:
    metadata:
      name: redis-staging-secret
      namespace: redis
    type: Opaque
